var a = 2, b = 1;
// --a;
// console.log(a);
// --b;
// console.log(b);
// ++b;
// console.log(b);
//b--;
//console.log(b);
console.log("a is " +a);
console.log("b is " +b);
var result= --a - --b + ++b + b --;
console.log("result is " +result);
//var result = --a - --b + ++b + b--;
//console.log(result);
//--a;
//console.log("The value of" +a);
//--a - --b;
//--a - --b + ++b;
//--a - --b + ++b + b--;